# Generated by Django 5.2.1 on 2025-05-30 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('expected_payoff_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deferred', 'Deferred'), ('paid', 'Paid Off')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
