# Generated by Django 5.2.1 on 2025-05-30 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoan',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('loanAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loanInterestRate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loanStartDate', models.DateField()),
                ('loanID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.loantype')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanProfile',
        ),
    ]
