# Generated by Django 5.2.1 on 2025-05-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_loantype_userloan_delete_loanprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanID', models.AutoField(primary_key=True, serialize=False)),
                ('loanProvider', models.CharField(max_length=100)),
                ('loanSite', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userloan',
            name='loanID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.loan'),
        ),
        migrations.DeleteModel(
            name='LoanType',
        ),
    ]
